//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer_Droid.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlagMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlagMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer_Droid.Consts.FlagMultilangConst", typeof(FlagMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Link copied ✅ 的本地化字符串。
        /// </summary>
        internal static string _LinkCopiedToastMsg {
            get {
                return ResourceManager.GetString("_LinkCopiedToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {}Now, let&apos;s turn on the &quot;Enable command line on non-rooted devices&quot; option in {0}
        ///
        ///Just tap the Copy Link button below, open it in {0}, and set the option to Enabled
        ///
        ///(If u run into any probs, feel free 2 join our chat 4 help) 的本地化字符串。
        /// </summary>
        internal static string GuideLabelText {
            get {
                return ResourceManager.GetString("GuideLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (Huh? Director, how did he get here so quickly? The script didn’t say that)
        ///
        ///Now, let’s turn on... uh... the selected browser’s...
        ///
        ///Uh, wait a moment, I’m not done memorizing my lines yet 的本地化字符串。
        /// </summary>
        internal static string GuideLabelTextBrowserNameFallback {
            get {
                return ResourceManager.GetString("GuideLabelTextBrowserNameFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Link 的本地化字符串。
        /// </summary>
        internal static string LinkButtonText {
            get {
                return ResourceManager.GetString("LinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to copy a flag jump link 的本地化字符串。
        /// </summary>
        internal static string LinkButtonTooltip {
            get {
                return ResourceManager.GetString("LinkButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ✨ Nice Work 🌟 的本地化字符串。
        /// </summary>
        internal static string TitleLabelText {
            get {
                return ResourceManager.GetString("TitleLabelText", resourceCulture);
            }
        }
    }
}
