//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer_Droid.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer_Droid.Consts.GlobalMultilangConst", typeof(GlobalMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Other (Custom) 的本地化字符串。
        /// </summary>
        internal static string _BrowserNameCollectionCustomTitle {
            get {
                return ResourceManager.GetString("_BrowserNameCollectionCustomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command copied ✅ 的本地化字符串。
        /// </summary>
        internal static string _CommandCopiedToastMsg {
            get {
                return ResourceManager.GetString("_CommandCopiedToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose whether to apply or delete the option 的本地化字符串。
        /// </summary>
        internal static string _CustomBrowserNameApplyPopupMsg {
            get {
                return ResourceManager.GetString("_CustomBrowserNameApplyPopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Custom Browser 的本地化字符串。
        /// </summary>
        internal static string _CustomBrowserNameApplyPopupTitle {
            get {
                return ResourceManager.GetString("_CustomBrowserNameApplyPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser name cannot be empty or contain whitespace characters ❌ 的本地化字符串。
        /// </summary>
        internal static string _CustomBrowserNameErrorToastMsg {
            get {
                return ResourceManager.GetString("_CustomBrowserNameErrorToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a Chromium-based browser name
        ///
        ///(Must support opening chrome://flags) 的本地化字符串。
        /// </summary>
        internal static string _CustomBrowserNamePopupMsg {
            get {
                return ResourceManager.GetString("_CustomBrowserNamePopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Browser Name 的本地化字符串。
        /// </summary>
        internal static string _CustomBrowserNamePopupTitle {
            get {
                return ResourceManager.GetString("_CustomBrowserNamePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yana from a parallel universe may tell you the answer 🌌 的本地化字符串。
        /// </summary>
        internal static string _DualThemeColorPairCancelToastMsg {
            get {
                return ResourceManager.GetString("_DualThemeColorPairCancelToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Wrong, you baka&quot; Yana ate your reman 🍜 的本地化字符串。
        /// </summary>
        internal static string _DualThemeColorPairErrorToastMsg {
            get {
                return ResourceManager.GetString("_DualThemeColorPairErrorToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Oh, wait a second&quot; Yana took away the reman in your hand
        ///
        ///&quot;{0}&quot; Some mysterious letters came out of her mouth, then she tilted her head, as if waiting for you to answer something. Seeing Yana&apos;s radiant smile, you froze for a moment
        ///
        ///What was this? Your name? Cold sweat ran down your back. But now you had no choice but to say something. What should you say 的本地化字符串。
        /// </summary>
        internal static string _DualThemeColorPairPopupMsg {
            get {
                return ResourceManager.GetString("_DualThemeColorPairPopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yana took away your reman 的本地化字符串。
        /// </summary>
        internal static string _DualThemeColorPairPopupTitle {
            get {
                return ResourceManager.GetString("_DualThemeColorPairPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;That&apos;s my code, you baka&quot; Yana ate your reman 🍜 的本地化字符串。
        /// </summary>
        internal static string _DualThemeColorPairRepeatToastMsg {
            get {
                return ResourceManager.GetString("_DualThemeColorPairRepeatToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Bingo! Correct code&quot;. Restart to taste narutomaki reman 🍥 的本地化字符串。
        /// </summary>
        internal static string _DualThemeColorPairSuccessToastMsg {
            get {
                return ResourceManager.GetString("_DualThemeColorPairSuccessToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        internal static string _LangOptionChineseName {
            get {
                return ResourceManager.GetString("_LangOptionChineseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 American English 的本地化字符串。
        /// </summary>
        internal static string _LangOptionEnglishName {
            get {
                return ResourceManager.GetString("_LangOptionEnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lang is changing. Restart to view the new lang 🌐 的本地化字符串。
        /// </summary>
        internal static string _LangOptionRestartToApplyToastMsg {
            get {
                return ResourceManager.GetString("_LangOptionRestartToApplyToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow System 的本地化字符串。
        /// </summary>
        internal static string _LangOptionUnspecifiedName {
            get {
                return ResourceManager.GetString("_LangOptionUnspecifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link copied ✅ 的本地化字符串。
        /// </summary>
        internal static string _LinkCopiedToastMsg {
            get {
                return ResourceManager.GetString("_LinkCopiedToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accept 的本地化字符串。
        /// </summary>
        internal static string _PopupAcceptText {
            get {
                return ResourceManager.GetString("_PopupAcceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string _PopupApplyText {
            get {
                return ResourceManager.GetString("_PopupApplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string _PopupCancelText {
            get {
                return ResourceManager.GetString("_PopupCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string _PopupDeleteText {
            get {
                return ResourceManager.GetString("_PopupDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        internal static string _PopupNoText {
            get {
                return ResourceManager.GetString("_PopupNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        internal static string _PopupYesText {
            get {
                return ResourceManager.GetString("_PopupYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting is changing. Restart to apply the new config 🔄 的本地化字符串。
        /// </summary>
        internal static string _SettingsRestartToApplyToastMsg {
            get {
                return ResourceManager.GetString("_SettingsRestartToApplyToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Where are you going? Come back 😟 的本地化字符串。
        /// </summary>
        internal static string _SkipWarning1ToastMsg {
            get {
                return ResourceManager.GetString("_SkipWarning1ToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get back here! No skipping allowed 😡 的本地化字符串。
        /// </summary>
        internal static string _SkipWarning2ToastMsg {
            get {
                return ResourceManager.GetString("_SkipWarning2ToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 How about we explore the area ahead of us later 😇 的本地化字符串。
        /// </summary>
        internal static string _SkipWarning3ToastMsg {
            get {
                return ResourceManager.GetString("_SkipWarning3ToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 U&apos;r not there yet 😮 的本地化字符串。
        /// </summary>
        internal static string _SkipWarning4ToastMsg {
            get {
                return ResourceManager.GetString("_SkipWarning4ToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Triple Ice Cream 的本地化字符串。
        /// </summary>
        internal static string _ThemeColorBlueName {
            get {
                return ResourceManager.GetString("_ThemeColorBlueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tetraploid Melon 的本地化字符串。
        /// </summary>
        internal static string _ThemeColorGreenName {
            get {
                return ResourceManager.GetString("_ThemeColorGreenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hexavalent Orange Juice 的本地化字符串。
        /// </summary>
        internal static string _ThemeColorOrangeName {
            get {
                return ResourceManager.GetString("_ThemeColorOrangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yana Narutomaki Ramen 的本地化字符串。
        /// </summary>
        internal static string _ThemeColorPinkBlueName {
            get {
                return ResourceManager.GetString("_ThemeColorPinkBlueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A Strawberry Milk 的本地化字符串。
        /// </summary>
        internal static string _ThemeColorRedName {
            get {
                return ResourceManager.GetString("_ThemeColorRedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flavor is changing. Restart to taste the new flavor 🍹 的本地化字符串。
        /// </summary>
        internal static string _ThemeColorRestartToApplyToastMsg {
            get {
                return ResourceManager.GetString("_ThemeColorRestartToApplyToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dihydrate Citric Acid 的本地化字符串。
        /// </summary>
        internal static string _ThemeColorYellowName {
            get {
                return ResourceManager.GetString("_ThemeColorYellowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark Theme 的本地化字符串。
        /// </summary>
        internal static string _ThemeStateDarkName {
            get {
                return ResourceManager.GetString("_ThemeStateDarkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light Theme 的本地化字符串。
        /// </summary>
        internal static string _ThemeStateLightName {
            get {
                return ResourceManager.GetString("_ThemeStateLightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme is changing. Restart to enjoy the new theme 🎨 的本地化字符串。
        /// </summary>
        internal static string _ThemeStateRestartToApplyToastMsg {
            get {
                return ResourceManager.GetString("_ThemeStateRestartToApplyToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Follow System 的本地化字符串。
        /// </summary>
        internal static string _ThemeStateUnspecifiedName {
            get {
                return ResourceManager.GetString("_ThemeStateUnspecifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string AboutMenuItemTitle {
            get {
                return ResourceManager.GetString("AboutMenuItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a Chromium-based browser 的本地化字符串。
        /// </summary>
        internal static string BrowserPickerTitle {
            get {
                return ResourceManager.GetString("BrowserPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to open a browser selection pop-up 的本地化字符串。
        /// </summary>
        internal static string BrowserPickerTooltip {
            get {
                return ResourceManager.GetString("BrowserPickerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Command 的本地化字符串。
        /// </summary>
        internal static string CommandButtonText {
            get {
                return ResourceManager.GetString("CommandButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to copy an ADB command 的本地化字符串。
        /// </summary>
        internal static string CommandButtonTooltip {
            get {
                return ResourceManager.GetString("CommandButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Link 的本地化字符串。
        /// </summary>
        internal static string LinkButtonText {
            get {
                return ResourceManager.GetString("LinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to copy a flag jump link 的本地化字符串。
        /// </summary>
        internal static string LinkButtonTooltip {
            get {
                return ResourceManager.GetString("LinkButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next 的本地化字符串。
        /// </summary>
        internal static string NextButtonDescription {
            get {
                return ResourceManager.GetString("NextButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to proceed to the next step 的本地化字符串。
        /// </summary>
        internal static string NextButtonTooltip {
            get {
                return ResourceManager.GetString("NextButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prev 的本地化字符串。
        /// </summary>
        internal static string PrevButtonDescription {
            get {
                return ResourceManager.GetString("PrevButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to return to the previous step 的本地化字符串。
        /// </summary>
        internal static string PrevButtonTooltip {
            get {
                return ResourceManager.GetString("PrevButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string SettingsMenuItemTitle {
            get {
                return ResourceManager.GetString("SettingsMenuItemTitle", resourceCulture);
            }
        }
    }
}
