//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer_Droid.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer_Droid.Consts.MainMultilangConst", typeof(MainMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Injection complete. Use the browser to test 的本地化字符串。
        /// </summary>
        internal static string _ActiveStatusMessage {
            get {
                return ResourceManager.GetString("_ActiveStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Injection is inactive. Tap the button to start 的本地化字符串。
        /// </summary>
        internal static string _InactiveStatusMessage {
            get {
                return ResourceManager.GetString("_InactiveStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Partial injection complete. Use the browser to test 的本地化字符串。
        /// </summary>
        internal static string _PartialStatusMessage {
            get {
                return ResourceManager.GetString("_PartialStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to jump to the download page 的本地化字符串。
        /// </summary>
        internal static string _UpdateAvailablePopupMsg {
            get {
                return ResourceManager.GetString("_UpdateAvailablePopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Software update is available 的本地化字符串。
        /// </summary>
        internal static string _UpdateAvailablePopupTitle {
            get {
                return ResourceManager.GetString("_UpdateAvailablePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host update available. Tap the button to update 的本地化字符串。
        /// </summary>
        internal static string _UpdateStatusMessage {
            get {
                return ResourceManager.GetString("_UpdateStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github 的本地化字符串。
        /// </summary>
        internal static string GithubToolbarItemDescription {
            get {
                return ResourceManager.GetString("GithubToolbarItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to jump to my github repo 的本地化字符串。
        /// </summary>
        internal static string GithubToolbarItemTooltip {
            get {
                return ResourceManager.GetString("GithubToolbarItemTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to stop cealing 的本地化字符串。
        /// </summary>
        internal static string LaunchButtonActiveTooltip {
            get {
                return ResourceManager.GetString("LaunchButtonActiveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch 的本地化字符串。
        /// </summary>
        internal static string LaunchButtonDescription {
            get {
                return ResourceManager.GetString("LaunchButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to start cealing 的本地化字符串。
        /// </summary>
        internal static string LaunchButtonInactiveTooltip {
            get {
                return ResourceManager.GetString("LaunchButtonInactiveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to update host 的本地化字符串。
        /// </summary>
        internal static string LaunchButtonUpdateTooltip {
            get {
                return ResourceManager.GetString("LaunchButtonUpdateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string MainSearchHandlerClearIconName {
            get {
                return ResourceManager.GetString("MainSearchHandlerClearIconName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search for host 的本地化字符串。
        /// </summary>
        internal static string MainSearchHandlerPlaceholder {
            get {
                return ResourceManager.GetString("MainSearchHandlerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        internal static string MainSearchHandlerQueryIconName {
            get {
                return ResourceManager.GetString("MainSearchHandlerQueryIconName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check host for update 的本地化字符串。
        /// </summary>
        internal static string UpdateToolbarItemText {
            get {
                return ResourceManager.GetString("UpdateToolbarItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to check host for update 的本地化字符串。
        /// </summary>
        internal static string UpdateToolbarItemTooltip {
            get {
                return ResourceManager.GetString("UpdateToolbarItemTooltip", resourceCulture);
            }
        }
    }
}
