//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer_Droid.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer_Droid.Consts.SettingsMultilangConst", typeof(SettingsMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Browser 的本地化字符串。
        /// </summary>
        internal static string BrowserSettingsItemTitle {
            get {
                return ResourceManager.GetString("BrowserSettingsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the ADB command to create a &quot;chrome-command-line&quot; file 的本地化字符串。
        /// </summary>
        internal static string CommandSettingsItemContent {
            get {
                return ResourceManager.GetString("CommandSettingsItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Adb Command 的本地化字符串。
        /// </summary>
        internal static string CommandSettingsItemTitle {
            get {
                return ResourceManager.GetString("CommandSettingsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the link to toggle the &quot;Enable command line on non-rooted devices&quot; option in a browser 的本地化字符串。
        /// </summary>
        internal static string LinkSettingsItemContent {
            get {
                return ResourceManager.GetString("LinkSettingsItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flag Link 的本地化字符串。
        /// </summary>
        internal static string LinkSettingsItemTitle {
            get {
                return ResourceManager.GetString("LinkSettingsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control whether to enable the host search feature (The search icon has a difficult-to-fix color issue in light mode. You can disable this option to hide it) 的本地化字符串。
        /// </summary>
        internal static string SearchEnabledSettingsItemContent {
            get {
                return ResourceManager.GetString("SearchEnabledSettingsItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Search 的本地化字符串。
        /// </summary>
        internal static string SearchEnabledSettingsItemTitle {
            get {
                return ResourceManager.GetString("SearchEnabledSettingsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to toggle the search feature on / off 的本地化字符串。
        /// </summary>
        internal static string SearchEnabledSwitchTooltip {
            get {
                return ResourceManager.GetString("SearchEnabledSwitchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a UI color flavor 的本地化字符串。
        /// </summary>
        internal static string ThemeColorPickerTitle {
            get {
                return ResourceManager.GetString("ThemeColorPickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to open a flavor color selection pop-up 的本地化字符串。
        /// </summary>
        internal static string ThemeColorPickerTooltip {
            get {
                return ResourceManager.GetString("ThemeColorPickerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flavor Color 的本地化字符串。
        /// </summary>
        internal static string ThemeColorSettingsItemTitle {
            get {
                return ResourceManager.GetString("ThemeColorSettingsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control whether to check host for update automatically on startup 的本地化字符串。
        /// </summary>
        internal static string UpdateHostEnabledSettingsItemContent {
            get {
                return ResourceManager.GetString("UpdateHostEnabledSettingsItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Check Host For Update 的本地化字符串。
        /// </summary>
        internal static string UpdateHostEnabledSettingsItemTitle {
            get {
                return ResourceManager.GetString("UpdateHostEnabledSettingsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to toggle the auto check host for update feature on / off 的本地化字符串。
        /// </summary>
        internal static string UpdateHostEnabledSwitchTooltip {
            get {
                return ResourceManager.GetString("UpdateHostEnabledSwitchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control whether to check software for update automatically on startup 的本地化字符串。
        /// </summary>
        internal static string UpdateSoftwareEnabledSettingsItemContent {
            get {
                return ResourceManager.GetString("UpdateSoftwareEnabledSettingsItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Check Software For Update 的本地化字符串。
        /// </summary>
        internal static string UpdateSoftwareEnabledSettingsItemTitle {
            get {
                return ResourceManager.GetString("UpdateSoftwareEnabledSettingsItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to toggle the auto check software for update feature on / off 的本地化字符串。
        /// </summary>
        internal static string UpdateSoftwareEnabledSwitchTooltip {
            get {
                return ResourceManager.GetString("UpdateSoftwareEnabledSwitchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to edit the upstream host updating source 的本地化字符串。
        /// </summary>
        internal static string UpstreamUrlEntryTooltip {
            get {
                return ResourceManager.GetString("UpstreamUrlEntryTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host Source 的本地化字符串。
        /// </summary>
        internal static string UpstreamUrlSettingsItemTitle {
            get {
                return ResourceManager.GetString("UpstreamUrlSettingsItemTitle", resourceCulture);
            }
        }
    }
}
