//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sheas_Cealer_Droid.Consts {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolMultilangConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolMultilangConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sheas_Cealer_Droid.Consts.ToolMultilangConst", typeof(ToolMultilangConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Enter a domain name to be resolved 的本地化字符串。
        /// </summary>
        internal static string _DohDomainNamePopupMsg {
            get {
                return ResourceManager.GetString("_DohDomainNamePopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Domain Name 的本地化字符串。
        /// </summary>
        internal static string _DohDomainNamePopupTitle {
            get {
                return ResourceManager.GetString("_DohDomainNamePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution failed. Very sorry nya ❌ 的本地化字符串。
        /// </summary>
        internal static string _DohResolveErrorToastMsg {
            get {
                return ResourceManager.GetString("_DohResolveErrorToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid domain format. Recognition failed ❌ 的本地化字符串。
        /// </summary>
        internal static string _DohResolveInvalidToastMsg {
            get {
                return ResourceManager.GetString("_DohResolveInvalidToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution successful. IP copied ✅ 的本地化字符串。
        /// </summary>
        internal static string _DohResolveSuccessToastMsg {
            get {
                return ResourceManager.GetString("_DohResolveSuccessToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection failed. Current network does not support IPv6 ❌ 的本地化字符串。
        /// </summary>
        internal static string _Ipv6TestErrorToastMsg {
            get {
                return ResourceManager.GetString("_Ipv6TestErrorToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection successful. Local network supports IPv6 ✅ 的本地化字符串。
        /// </summary>
        internal static string _Ipv6TestSuccessToastMsg {
            get {
                return ResourceManager.GetString("_Ipv6TestSuccessToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter an address to test ping connectivity 的本地化字符串。
        /// </summary>
        internal static string _PingHostNamePopupMsg {
            get {
                return ResourceManager.GetString("_PingHostNamePopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string _PingHostNamePopupTitle {
            get {
                return ResourceManager.GetString("_PingHostNamePopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection failed. Current address can not be pinged ❌ 的本地化字符串。
        /// </summary>
        internal static string _PingTestErrorToastMsg {
            get {
                return ResourceManager.GetString("_PingTestErrorToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid address format. Recognition failed ❌ 的本地化字符串。
        /// </summary>
        internal static string _PingTestInvalidToastMsg {
            get {
                return ResourceManager.GetString("_PingTestInvalidToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection cancelled. DNS returned a reserved IP ❌ 的本地化字符串。
        /// </summary>
        internal static string _PingTestReversedToastMsg {
            get {
                return ResourceManager.GetString("_PingTestReversedToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connection successful. Current address can be pinged ✅ 的本地化字符串。
        /// </summary>
        internal static string _PingTestSuccessToastMsg {
            get {
                return ResourceManager.GetString("_PingTestSuccessToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter an IP to be checked 的本地化字符串。
        /// </summary>
        internal static string _ReserveCheckHostPopupMsg {
            get {
                return ResourceManager.GetString("_ReserveCheckHostPopupMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP 的本地化字符串。
        /// </summary>
        internal static string _ReserveCheckHostPopupTitle {
            get {
                return ResourceManager.GetString("_ReserveCheckHostPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid IP format. Recognition failed ❌ 的本地化字符串。
        /// </summary>
        internal static string _ReserveCheckInvalidToastMsg {
            get {
                return ResourceManager.GetString("_ReserveCheckInvalidToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match successful. Current IP is not a reserved IP ✅ 的本地化字符串。
        /// </summary>
        internal static string _ReserveCheckNonreversedToastMsg {
            get {
                return ResourceManager.GetString("_ReserveCheckNonreversedToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Match successful. Current IP is a reserved IP ✅ 的本地化字符串。
        /// </summary>
        internal static string _ReserveCheckReversedToastMsg {
            get {
                return ResourceManager.GetString("_ReserveCheckReversedToastMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolve 的本地化字符串。
        /// </summary>
        internal static string DohImageButtonDescription {
            get {
                return ResourceManager.GetString("DohImageButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to open a DoH resolution pop-up 的本地化字符串。
        /// </summary>
        internal static string DohImageButtonTooltip {
            get {
                return ResourceManager.GetString("DohImageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolve any domain via DoH 的本地化字符串。
        /// </summary>
        internal static string DohToolItemContent {
            get {
                return ResourceManager.GetString("DohToolItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoH Resolution 的本地化字符串。
        /// </summary>
        internal static string DohToolItemTitle {
            get {
                return ResourceManager.GetString("DohToolItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test 的本地化字符串。
        /// </summary>
        internal static string Ipv6ImageButtonDescription {
            get {
                return ResourceManager.GetString("Ipv6ImageButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to start an IPv6 accessibility test 的本地化字符串。
        /// </summary>
        internal static string Ipv6ImageButtonTooltip {
            get {
                return ResourceManager.GetString("Ipv6ImageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test whether the local network environment can access IPv6 的本地化字符串。
        /// </summary>
        internal static string Ipv6ToolItemContent {
            get {
                return ResourceManager.GetString("Ipv6ToolItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPv6 Test 的本地化字符串。
        /// </summary>
        internal static string Ipv6ToolItemTitle {
            get {
                return ResourceManager.GetString("Ipv6ToolItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ping 的本地化字符串。
        /// </summary>
        internal static string PingImageButtonDescription {
            get {
                return ResourceManager.GetString("PingImageButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to open a ping connectivity test pop-up 的本地化字符串。
        /// </summary>
        internal static string PingImageButtonTooltip {
            get {
                return ResourceManager.GetString("PingImageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test whether the local network can ping specified address 的本地化字符串。
        /// </summary>
        internal static string PingToolItemContent {
            get {
                return ResourceManager.GetString("PingToolItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ping Test 的本地化字符串。
        /// </summary>
        internal static string PingToolItemTitle {
            get {
                return ResourceManager.GetString("PingToolItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        internal static string ReserveImageButtonDescription {
            get {
                return ResourceManager.GetString("ReserveImageButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tap to open a reserved IP check pop-up 的本地化字符串。
        /// </summary>
        internal static string ReserveImageButtonTooltip {
            get {
                return ResourceManager.GetString("ReserveImageButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check whether the specified IP is a reserved IP 的本地化字符串。
        /// </summary>
        internal static string ReserveToolItemContent {
            get {
                return ResourceManager.GetString("ReserveToolItemContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reserved IP Check 的本地化字符串。
        /// </summary>
        internal static string ReserveToolItemTitle {
            get {
                return ResourceManager.GetString("ReserveToolItemTitle", resourceCulture);
            }
        }
    }
}
